### ISSUE TITLE
Audit Circle Meeting 5  - 12th May 2022 - Agenda & Notes

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Audit-Hub-Coordination#24]
## Audit Circle Meeting 5 - 12th May 2022 - Agenda & Notes 

https://quality-assurance-dao.gitbook.io/audit-circle/project-management/meetings/

**Comment by PolymathGirl** [comment]
Here's what I've got so far. There might be a few pieces that could be rearranged or formatted a bit differently, but I think among the highlights it should make pretty good sense. 
[Audit Circle Meeting #5 notes](https://docs.google.com/document/d/1ESAsGC6BQVEDOrxj_1J3O7axI-lbM0BuMe7-JgMri6g/edit?usp=sharing)

Here is my revised/corrected version of the otter.io transcript
[Audit_Circle_Meeting_5 - otter.ai transcript - Megans Edits.docx](https://github.com/Catalyst-Auditing/Audit-Circle-Coordination/files/8704357/Audit_Circle_Meeting_5.-.otter.ai.transcript.-.Megans.Edits.docx)

Let me know if there's anything that looks off, or to tweak further, for clarity.

**Comment by Andre-Diamond** [comment]
Payment done on May 12th, transaction can be viewed [here](https://raw.githubusercontent.com/treasuryguild/Community-Governance-Oversight/main/Transactions/Fund7/Catalyst-Audit-Circle/Meeting-Minutes/1652379016185-Megan.json) or [here](https://treasury-guild.gitbook.io/community-governance-oversight/transactions/fund-7/catalyst-audit-circle).
