### ISSUE TITLE
Project Catalyst Weekly Newsletter - Friday, 15th April 2022

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Auditing/Audit-Hub-Coordination#8]
## Project Catalyst Weekly Newsletter - Friday, 15th April 2022

![2022-04-12 (3)](https://user-images.githubusercontent.com/25156451/163571599-bd31c555-05e4-45e5-8700-344f8c4f85f1.png)

>"This week [Audit Circle](https://quality-assurance-dao.gitbook.io/audit-circle/) met for the third time. Thorsten Pottebaum gave feedback on an "[Update Audit](https://youtu.be/jMFzi25bmzQ)" After Town Hall discussion he hosted on Wednesday, 13th April 2022. Some major themes that emerged included transparency of reporting, tailoring auditability to the scale of a proposal’s budget and release of funds on delivery. A more comprehensive review will follow.
> The meeting also discussed one of Audit Circle’s key deliverables: internal and external surveys about the proposal audit process. We decided that one useful focus would be to investigate how proposers monitor their projects and gather the data that is needed for effective audit.
> The future scope of Audit Circle was also covered, and possible expansion beyond oversight and into possible thought leadership and guidance. Consensus was not reached on this; there will be more discussion in future meetings."

**Comment by fhilipk** [comment]
The Audit Circle spent some time discussing its future scope and possible involvement in expanded participation beyond oversight and into possible thought leadership and guidance. Consensus was not reached on if this and more discussion with be required.

**Comment by VanCardui** [comment]
How's this (incorporating Phil's above)

_"This week [Audit Circle](https://quality-assurance-dao.gitbook.io/audit-circle/) met for the third time. 
Thorsten Pottebaum gave feedback on the "[Update Audit](https://youtu.be/jMFzi25bmzQ)" After Town Hall discussion that he led on Weds 13th . Some major themes that emerged included transparency of reporting, tailoring auditability to the scale of a proposal’s budget, and release of funds on delivery. A more comprehensive review will follow.
The meeting also discussed one of Audit Circle’s key deliverables: internal and external surveys about the proposal audit process. We decided that one useful focus would be to investigate how proposers monitor their projects and gather the data that is needed for effective audit.
The meeting also covered the future scope of Audit Circle, and possible expansion beyond oversight and into possible thought leadership and guidance. Consensus was not reached on this; there will be more discussion in future meetings._
